[project]
name = "seviper"
description = "A simple and easy to use library to catch and handle exceptions."
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [{ name = "Leon Haffmans", email = "leon.haffmans@hochfrequenz.de" }]
keywords = ["error-handling", "aiostream"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []     # add all the dependencies here
dynamic = ["readme", "version"]

[project.optional-dependencies]
aiostream = [
    "aiostream"
    # seviper[aiostream], just like seviper[coverage], seviper[formatting], ... are optional dependencies, which are not required for the bare seviper logic to work.
    # We have to distinguish between those optional dependencies which are intended for the users of seviper (like `seviper[aiostream]` which we mention in our README).
    # Those are NOT pinned because seviper works with any recent version of aiostream and we don't want to restrict the users of the library.
    # But those optional dependencies which we only use for our (internal) CI/CD pipeline (like coverage, formatting etc.) are pinned,
    # because they are not inteded for external use but give us a stable and reproducable CI and dev experience.
]
coverage = [
    "coverage==7.8.2"
]
formatting = [
    "black==25.1.0",
    "isort==6.0.1"
]
linting = [
    "pylint==3.3.7"
]
spellcheck = [
    "codespell==2.4.1"
]
test_packaging = [
    "build==1.2.2.post1",
    "twine==6.1.0"
]
tests = [
    "pytest==8.4.0",
    "pytest-asyncio==0.26.0"
]
type_check = [
    "mypy==1.16.0"
]

[project.urls]
Changelog = "https://github.com/Hochfrequenz/seviper/releases"
Homepage = "https://github.com/Hochfrequenz/seviper"

[tool.black]
line-length = 120
target_version = ["py312", "py313"]

[tool.isort]
line_length = 120
profile = "black"

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120

[build-system]
requires = ["hatchling>=1.8.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [{ path = "README.md" }]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/_error_handler_version.py"
template = '''
version = "{version}"
'''

[tool.hatch.build.targets.sdist]
exclude = ["/unittests"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
