name: "Linting"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pylint:
    name: "Python Code Quality and Lint (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.group }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
        group: ["linting", "type_check", "spell_check"]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run linting
        if: matrix.group == 'linting'
        run: |
          uv run --group linting ruff check src/error_handler unittests
      - name: Run type_check
        if: matrix.group == 'type_check'
        run: |
          uv run --group type_check mypy --show-error-codes src/error_handler
          uv run --group type_check mypy --show-error-codes unittests
      - name: Run spell_check
        if: matrix.group == 'spell_check'
        run: |
          uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt src
          uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt README.md
